# Generated by Django 4.1.7 on 2023-03-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video_WBG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadDate', models.DateField(auto_now=True)),
                ('uploadTime', models.TimeField(auto_now=True)),
                ('video', models.FileField(upload_to='Nerf3dGenerator/video/')),
                ('status', models.CharField(default='FAILED', max_length=25)),
            ],
        ),
    ]
