# Generated by Django 4.1.7 on 2023-03-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nerf3dGenerator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_wbg',
            name='video',
            field=models.FileField(upload_to='Nerf3dGenerator/Dataset/'),
        ),
    ]
