# Generated by Django 4.1.7 on 2023-04-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nerf3dGenerator', '0002_alter_video_wbg_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimensioned_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadDate', models.DateField(auto_now=True)),
                ('uploadTime', models.TimeField(auto_now=True)),
                ('videoPath', models.CharField(max_length=265)),
                ('status', models.CharField(default='FAILED', max_length=25)),
            ],
        ),
    ]
